name: Build and publish NuGet package

on:
  push:
    tags:
      - 'v*' # 当推送带有 'v' 前缀的 tag 时触发 workflow

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' 

      - name: Build
        run: dotnet build src/AbpHelper.Core/AbpHelper.Core.csproj --configuration Release # 指定 lib 项目文件路径

      - name: Pack
        run: dotnet pack src/AbpHelper.Core/AbpHelper.Core.csproj --configuration Release --output ./nupkg # 指定 lib 项目文件路径

      - name: Publish NuGet package
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: ./nupkg/*.nupkg

      - name: Publish to NuGet.org
        run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
        if: startsWith(github.ref, 'refs/tags/v') # 只在 tag 推送到仓库时发布